In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataframe = pd.read_csv('train.csv')
dataframe["Name"], dataframe["Pclass"] = dataframe["Pclass"], dataframe["Name"] 
dataframe = dataframe.rename(columns={"Pclass":"Name", "Name":"Pclass"})
dataframe = np.array(dataframe)
dataframe[: ,[8,9]] = dataframe[: ,[9,8]]
test = pd.read_csv('test.csv')
PassengerId = test.iloc[: ,0:1].values
test["Name"], test["Pclass"] = test["Pclass"], test["Name"]
test = test.rename(columns={"Pclass":"Name", "Name":"Pclass"})
test = np.array(test)
test[: ,[7,8]] = test[: ,[8,7]]
test

array([[892, 'Kelly, Mr. James', 3, ..., '330911', nan, 'Q'],
       [893, 'Wilkes, Mrs. James (Ellen Needs)', 3, ..., '363272', nan,
        'S'],
       [894, 'Myles, Mr. Thomas Francis', 2, ..., '240276', nan, 'Q'],
       ...,
       [1307, 'Saether, Mr. Simon Sivertsen', 3, ...,
        'SOTON/O.Q. 3101262', nan, 'S'],
       [1308, 'Ware, Mr. Frederick', 3, ..., '359309', nan, 'S'],
       [1309, 'Peter, Master. Michael J', 3, ..., '2668', nan, 'C']],
      dtype=object)

In [ ]:
X = dataframe[: ,3:10]
y = dataframe[: ,1]
test = test[: ,2:9]
y = np.array(y) 
y=y.astype('int')

In [ ]:
print(test)

[[3 'male' 34.5 ... 0 'Q' 7.8292]
 [3 'female' 47.0 ... 0 'S' 7.0]
 [2 'male' 62.0 ... 0 'Q' 9.6875]
 ...
 [3 'male' 38.5 ... 0 'S' 7.25]
 [3 'male' nan ... 0 'S' 8.05]
 [3 'male' nan ... 1 'C' 22.3583]]


In [ ]:
print(X)

[[3 'male' 22.0 ... 0 'S' 7.25]
 [1 'female' 38.0 ... 0 'C' 71.2833]
 [3 'female' 26.0 ... 0 'S' 7.925]
 ...
 [3 'female' nan ... 2 'S' 23.45]
 [1 'male' 26.0 ... 0 'C' 30.0]
 [3 'male' 32.0 ... 0 'Q' 7.75]]


In [ ]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values = np.nan, strategy = "most_frequent")
si.fit(X)
X = si.transform(X)
si_test = SimpleImputer(missing_values = np.nan, strategy = "most_frequent")
si_test.fit(test)
test = si_test.transform(test)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1,-2])], remainder = 'passthrough') 
X = ct.fit_transform(X) 
ct_test = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1,-2])], remainder = 'passthrough')
test = ct_test.fit_transform(test) 

In [ ]:
X[0]

array([0.0, 1.0, 0.0, 0.0, 1.0, 3, 22.0, 1, 0, 7.25], dtype=object)

In [ ]:
test[1]

array([1.0, 0.0, 0.0, 0.0, 1.0, 3, 47.0, 1, 0, 7.0], dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X[: ,-4:] = sc.fit_transform(X[: ,-4:])
test[: ,-4:] = sc.transform(test[: ,-4:])

In [ ]:
X

array([[0.0, 1.0, 0.0, ..., 0.43279336567850346, -0.473673609298456,
        -0.5024451714361915],
       [1.0, 0.0, 1.0, ..., 0.43279336567850346, -0.473673609298456,
        0.7868452935884467],
       [1.0, 0.0, 0.0, ..., -0.4745451962498414, -0.473673609298456,
        -0.4888542575852478],
       ...,
       [1.0, 0.0, 0.0, ..., 0.43279336567850346, 2.0089333664952163,
        -0.1762632390135436],
       [0.0, 1.0, 1.0, ..., -0.4745451962498414, -0.473673609298456,
        -0.0443810379414236],
       [0.0, 1.0, 0.0, ..., -0.4745451962498414, -0.473673609298456,
        -0.49237782784289985]], dtype=object)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 42)
classifier.fit(X, y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=42, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
len(y_pred)

418

Score obtained : 0.7799

In [ ]:
LR = KNN = 0.8161434977578476
SVC = 0.7847533632286996
SVM = 0.8251121076233184
NB = 0.7982062780269058
DT = 0.7488789237668162
DT_adaboost = 0.7847533632286996
RF = 0.7892376681614349